spring:
  application:
    name: ad-eureka
server:
  port: 8000

eureka:
  instance:
    #单机
    hostname: localhost
  client:
    #默认为true,同步eureka节点
    fetch-registry: false
    #默认为true，是否注册自己到eureka
    register-with-eureka: false
    #注册地址，不写也是这个地址
    service-url:
      defalutZone: http://${eureka.instance.hostname}:${server.port}